// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error)
	ListRemindersByOrg(ctx context.Context, orgID pgtype.UUID) ([]Reminder, error)
}

var _ Querier = (*Queries)(nil)
