// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (
    id, org_id, type, client_id, contract_id, note,
    desired_at, duration_minutes, scheduled_at, was_shifted, reason
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, org_id, type, client_id, contract_id, note,
          desired_at, duration_minutes, scheduled_at, was_shifted, reason, created_at
`

type CreateReminderParams struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	Type            string             `json:"type"`
	ClientID        pgtype.UUID        `json:"client_id"`
	ContractID      pgtype.UUID        `json:"contract_id"`
	Note            string             `json:"note"`
	DesiredAt       pgtype.Timestamptz `json:"desired_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	WasShifted      bool               `json:"was_shifted"`
	Reason          string             `json:"reason"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRow(ctx, createReminder,
		arg.ID,
		arg.OrgID,
		arg.Type,
		arg.ClientID,
		arg.ContractID,
		arg.Note,
		arg.DesiredAt,
		arg.DurationMinutes,
		arg.ScheduledAt,
		arg.WasShifted,
		arg.Reason,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Type,
		&i.ClientID,
		&i.ContractID,
		&i.Note,
		&i.DesiredAt,
		&i.DurationMinutes,
		&i.ScheduledAt,
		&i.WasShifted,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listRemindersByOrg = `-- name: ListRemindersByOrg :many
SELECT id, org_id, type, client_id, contract_id, note,
       desired_at, duration_minutes, scheduled_at, was_shifted, reason, created_at
FROM reminders
WHERE org_id = $1
ORDER BY scheduled_at ASC
`

func (q *Queries) ListRemindersByOrg(ctx context.Context, orgID pgtype.UUID) ([]Reminder, error) {
	rows, err := q.db.Query(ctx, listRemindersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reminder{}
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Type,
			&i.ClientID,
			&i.ContractID,
			&i.Note,
			&i.DesiredAt,
			&i.DurationMinutes,
			&i.ScheduledAt,
			&i.WasShifted,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
