// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TelegramUser struct {
	ChatID    int64              `json:"chat_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	Username  string             `json:"username"`
	FullName  string             `json:"full_name"`
	Phone     string             `json:"phone"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
