// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetTelegramUserByChatID(ctx context.Context, chatID int64) (TelegramUser, error)
	UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (TelegramUser, error)
	GetChatIDByClient(ctx context.Context, arg GetChatIDByClientParams) (int64, error)
	GetDefaultOrgID(ctx context.Context) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
