// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatIDByClient = `-- name: GetChatIDByClient :one
SELECT chat_id
FROM telegram_users
WHERE org_id = $1 AND client_id = $2 AND state = 'registered'
`

type GetChatIDByClientParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) GetChatIDByClient(ctx context.Context, arg GetChatIDByClientParams) (int64, error) {
	row := q.db.QueryRow(ctx, getChatIDByClient, arg.OrgID, arg.ClientID)
	var chat_id int64
	err := row.Scan(&chat_id)
	return chat_id, err
}

const getDefaultOrgID = `-- name: GetDefaultOrgID :one
SELECT id
FROM organizations
ORDER BY created_at
LIMIT 1
`

func (q *Queries) GetDefaultOrgID(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDefaultOrgID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTelegramUserByChatID = `-- name: GetTelegramUserByChatID :one
SELECT chat_id, org_id, client_id, username, full_name, phone, state, created_at, updated_at
FROM telegram_users
WHERE chat_id = $1
`

func (q *Queries) GetTelegramUserByChatID(ctx context.Context, chatID int64) (TelegramUser, error) {
	row := q.db.QueryRow(ctx, getTelegramUserByChatID, chatID)
	var i TelegramUser
	err := row.Scan(
		&i.ChatID,
		&i.OrgID,
		&i.ClientID,
		&i.Username,
		&i.FullName,
		&i.Phone,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO telegram_users (chat_id, org_id, client_id, username, full_name, phone, state)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (chat_id) DO UPDATE SET
    org_id = EXCLUDED.org_id,
    client_id = EXCLUDED.client_id,
    username = EXCLUDED.username,
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    state = EXCLUDED.state,
    updated_at = now()
RETURNING chat_id, org_id, client_id, username, full_name, phone, state, created_at, updated_at
`

type UpsertTelegramUserParams struct {
	ChatID   int64       `json:"chat_id"`
	OrgID    pgtype.UUID `json:"org_id"`
	ClientID pgtype.UUID `json:"client_id"`
	Username string      `json:"username"`
	FullName string      `json:"full_name"`
	Phone    string      `json:"phone"`
	State    string      `json:"state"`
}

func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (TelegramUser, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser,
		arg.ChatID,
		arg.OrgID,
		arg.ClientID,
		arg.Username,
		arg.FullName,
		arg.Phone,
		arg.State,
	)
	var i TelegramUser
	err := row.Scan(
		&i.ChatID,
		&i.OrgID,
		&i.ClientID,
		&i.Username,
		&i.FullName,
		&i.Phone,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
