// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: charity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCharityEntry = `-- name: CreateCharityEntry :one
INSERT INTO charity_entries (id, org_id, contract_id, client_id, amount, status, note, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, contract_id, client_id, amount, status, note, created_by, created_at
`

type CreateCharityEntryParams struct {
	ID         pgtype.UUID    `json:"id"`
	OrgID      pgtype.UUID    `json:"org_id"`
	ContractID pgtype.UUID    `json:"contract_id"`
	ClientID   pgtype.UUID    `json:"client_id"`
	Amount     pgtype.Numeric `json:"amount"`
	Status     string         `json:"status"`
	Note       string         `json:"note"`
	CreatedBy  pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateCharityEntry(ctx context.Context, arg CreateCharityEntryParams) (CharityEntry, error) {
	row := q.db.QueryRow(ctx, createCharityEntry,
		arg.ID,
		arg.OrgID,
		arg.ContractID,
		arg.ClientID,
		arg.Amount,
		arg.Status,
		arg.Note,
		arg.CreatedBy,
	)
	var i CharityEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ContractID,
		&i.ClientID,
		&i.Amount,
		&i.Status,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCharityByOrg = `-- name: ListCharityByOrg :many
SELECT id, org_id, contract_id, client_id, amount, status, note, created_by, created_at
FROM charity_entries
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCharityByOrg(ctx context.Context, orgID pgtype.UUID) ([]CharityEntry, error) {
	rows, err := q.db.Query(ctx, listCharityByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CharityEntry{}
	for rows.Next() {
		var i CharityEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ContractID,
			&i.ClientID,
			&i.Amount,
			&i.Status,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
