// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contracts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContract = `-- name: CreateContract :exec
INSERT INTO contracts (
    id, org_id, client_id, product_id,
    cost_price, markup, sale_price, down_payment, financed_amount, outstanding,
    installments_count, cadence, currency, status, start_date
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15
)
`

type CreateContractParams struct {
	ID                pgtype.UUID    `json:"id"`
	OrgID             pgtype.UUID    `json:"org_id"`
	ClientID          pgtype.UUID    `json:"client_id"`
	ProductID         pgtype.UUID    `json:"product_id"`
	CostPrice         pgtype.Numeric `json:"cost_price"`
	Markup            pgtype.Numeric `json:"markup"`
	SalePrice         pgtype.Numeric `json:"sale_price"`
	DownPayment       pgtype.Numeric `json:"down_payment"`
	FinancedAmount    pgtype.Numeric `json:"financed_amount"`
	Outstanding       pgtype.Numeric `json:"outstanding"`
	InstallmentsCount int32          `json:"installments_count"`
	Cadence           string         `json:"cadence"`
	Currency          string         `json:"currency"`
	Status            string         `json:"status"`
	StartDate         pgtype.Date    `json:"start_date"`
}

func (q *Queries) CreateContract(ctx context.Context, arg CreateContractParams) error {
	_, err := q.db.Exec(ctx, createContract,
		arg.ID,
		arg.OrgID,
		arg.ClientID,
		arg.ProductID,
		arg.CostPrice,
		arg.Markup,
		arg.SalePrice,
		arg.DownPayment,
		arg.FinancedAmount,
		arg.Outstanding,
		arg.InstallmentsCount,
		arg.Cadence,
		arg.Currency,
		arg.Status,
		arg.StartDate,
	)
	return err
}

const createInstallment = `-- name: CreateInstallment :exec
INSERT INTO installments (id, contract_id, number, due_date, amount)
VALUES ($1, $2, $3, $4, $5)
`

type CreateInstallmentParams struct {
	ID         pgtype.UUID    `json:"id"`
	ContractID pgtype.UUID    `json:"contract_id"`
	Number     int32          `json:"number"`
	DueDate    pgtype.Date    `json:"due_date"`
	Amount     pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) error {
	_, err := q.db.Exec(ctx, createInstallment,
		arg.ID,
		arg.ContractID,
		arg.Number,
		arg.DueDate,
		arg.Amount,
	)
	return err
}

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (id, contract_id, amount, paid_at)
VALUES ($1, $2, $3, $4)
`

type CreatePaymentParams struct {
	ID         pgtype.UUID        `json:"id"`
	ContractID pgtype.UUID        `json:"contract_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment,
		arg.ID,
		arg.ContractID,
		arg.Amount,
		arg.PaidAt,
	)
	return err
}

const getContractByID = `-- name: GetContractByID :one
SELECT id, org_id, client_id, product_id,
       cost_price, markup, sale_price, down_payment, financed_amount, outstanding,
       installments_count, cadence, currency, status, start_date, created_at
FROM contracts
WHERE id = $1 AND org_id = $2
`

type GetContractByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetContractByID(ctx context.Context, arg GetContractByIDParams) (Contract, error) {
	row := q.db.QueryRow(ctx, getContractByID, arg.ID, arg.OrgID)
	var i Contract
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientID,
		&i.ProductID,
		&i.CostPrice,
		&i.Markup,
		&i.SalePrice,
		&i.DownPayment,
		&i.FinancedAmount,
		&i.Outstanding,
		&i.InstallmentsCount,
		&i.Cadence,
		&i.Currency,
		&i.Status,
		&i.StartDate,
		&i.CreatedAt,
	)
	return i, err
}

const listContractsByOrg = `-- name: ListContractsByOrg :many
SELECT id, org_id, client_id, product_id,
       cost_price, markup, sale_price, down_payment, financed_amount, outstanding,
       installments_count, cadence, currency, status, start_date, created_at
FROM contracts
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContractsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Contract, error) {
	rows, err := q.db.Query(ctx, listContractsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contract{}
	for rows.Next() {
		var i Contract
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientID,
			&i.ProductID,
			&i.CostPrice,
			&i.Markup,
			&i.SalePrice,
			&i.DownPayment,
			&i.FinancedAmount,
			&i.Outstanding,
			&i.InstallmentsCount,
			&i.Cadence,
			&i.Currency,
			&i.Status,
			&i.StartDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstallmentsByContract = `-- name: ListInstallmentsByContract :many
SELECT id, contract_id, number, due_date, amount
FROM installments
WHERE contract_id = $1
ORDER BY number ASC
`

func (q *Queries) ListInstallmentsByContract(ctx context.Context, contractID pgtype.UUID) ([]Installment, error) {
	rows, err := q.db.Query(ctx, listInstallmentsByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Installment{}
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Number,
			&i.DueDate,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByContract = `-- name: ListPaymentsByContract :many
SELECT id, contract_id, amount, paid_at, created_at
FROM payments
WHERE contract_id = $1
ORDER BY paid_at ASC
`

func (q *Queries) ListPaymentsByContract(ctx context.Context, contractID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByContract, contractID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.ContractID,
			&i.Amount,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContractState = `-- name: UpdateContractState :exec
UPDATE contracts
SET outstanding = $3, status = $4
WHERE id = $1 AND org_id = $2
`

type UpdateContractStateParams struct {
	ID          pgtype.UUID    `json:"id"`
	OrgID       pgtype.UUID    `json:"org_id"`
	Outstanding pgtype.Numeric `json:"outstanding"`
	Status      string         `json:"status"`
}

func (q *Queries) UpdateContractState(ctx context.Context, arg UpdateContractStateParams) error {
	_, err := q.db.Exec(ctx, updateContractState,
		arg.ID,
		arg.OrgID,
		arg.Outstanding,
		arg.Status,
	)
	return err
}
