// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	KeyHash   string             `json:"key_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type CharityEntry struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	ContractID pgtype.UUID        `json:"contract_id"`
	ClientID   pgtype.UUID        `json:"client_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	Status     string             `json:"status"`
	Note       string             `json:"note"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Client struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	FullName  string             `json:"full_name"`
	Phone     string             `json:"phone"`
	Document  string             `json:"document"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Contract struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	ClientID          pgtype.UUID        `json:"client_id"`
	ProductID         pgtype.UUID        `json:"product_id"`
	CostPrice         pgtype.Numeric     `json:"cost_price"`
	Markup            pgtype.Numeric     `json:"markup"`
	SalePrice         pgtype.Numeric     `json:"sale_price"`
	DownPayment       pgtype.Numeric     `json:"down_payment"`
	FinancedAmount    pgtype.Numeric     `json:"financed_amount"`
	Outstanding       pgtype.Numeric     `json:"outstanding"`
	InstallmentsCount int32              `json:"installments_count"`
	Cadence           string             `json:"cadence"`
	Currency          string             `json:"currency"`
	Status            string             `json:"status"`
	StartDate         pgtype.Date        `json:"start_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Installment struct {
	ID         pgtype.UUID    `json:"id"`
	ContractID pgtype.UUID    `json:"contract_id"`
	Number     int32          `json:"number"`
	DueDate    pgtype.Date    `json:"due_date"`
	Amount     pgtype.Numeric `json:"amount"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID         pgtype.UUID        `json:"id"`
	ContractID pgtype.UUID        `json:"contract_id"`
	Amount     pgtype.Numeric     `json:"amount"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	CostPrice   pgtype.Numeric     `json:"cost_price"`
	HalalStatus string             `json:"halal_status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
