// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateContract(ctx context.Context, arg CreateContractParams) error
	CreateInstallment(ctx context.Context, arg CreateInstallmentParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	GetContractByID(ctx context.Context, arg GetContractByIDParams) (Contract, error)
	ListContractsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Contract, error)
	ListInstallmentsByContract(ctx context.Context, contractID pgtype.UUID) ([]Installment, error)
	ListPaymentsByContract(ctx context.Context, contractID pgtype.UUID) ([]Payment, error)
	UpdateContractState(ctx context.Context, arg UpdateContractStateParams) error
}

var _ Querier = (*Queries)(nil)
