// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContractRequest = `-- name: CreateContractRequest :one
INSERT INTO contract_requests (id, org_id, client_id, product_id, desired_installments, desired_down_payment, note, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, client_id, product_id, desired_installments, desired_down_payment, note, status, contract_id, created_at, decided_at
`

type CreateContractRequestParams struct {
	ID                  pgtype.UUID    `json:"id"`
	OrgID               pgtype.UUID    `json:"org_id"`
	ClientID            pgtype.UUID    `json:"client_id"`
	ProductID           pgtype.UUID    `json:"product_id"`
	DesiredInstallments int32          `json:"desired_installments"`
	DesiredDownPayment  pgtype.Numeric `json:"desired_down_payment"`
	Note                string         `json:"note"`
	Status              string         `json:"status"`
}

func (q *Queries) CreateContractRequest(ctx context.Context, arg CreateContractRequestParams) (ContractRequest, error) {
	row := q.db.QueryRow(ctx, createContractRequest,
		arg.ID,
		arg.OrgID,
		arg.ClientID,
		arg.ProductID,
		arg.DesiredInstallments,
		arg.DesiredDownPayment,
		arg.Note,
		arg.Status,
	)
	var i ContractRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientID,
		&i.ProductID,
		&i.DesiredInstallments,
		&i.DesiredDownPayment,
		&i.Note,
		&i.Status,
		&i.ContractID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getContractRequestByID = `-- name: GetContractRequestByID :one
SELECT id, org_id, client_id, product_id, desired_installments, desired_down_payment, note, status, contract_id, created_at, decided_at
FROM contract_requests
WHERE id = $1 AND org_id = $2
`

type GetContractRequestByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetContractRequestByID(ctx context.Context, arg GetContractRequestByIDParams) (ContractRequest, error) {
	row := q.db.QueryRow(ctx, getContractRequestByID, arg.ID, arg.OrgID)
	var i ContractRequest
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientID,
		&i.ProductID,
		&i.DesiredInstallments,
		&i.DesiredDownPayment,
		&i.Note,
		&i.Status,
		&i.ContractID,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listContractRequestsByClient = `-- name: ListContractRequestsByClient :many
SELECT id, org_id, client_id, product_id, desired_installments, desired_down_payment, note, status, contract_id, created_at, decided_at
FROM contract_requests
WHERE org_id = $1 AND client_id = $2
ORDER BY created_at DESC
`

type ListContractRequestsByClientParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) ListContractRequestsByClient(ctx context.Context, arg ListContractRequestsByClientParams) ([]ContractRequest, error) {
	rows, err := q.db.Query(ctx, listContractRequestsByClient, arg.OrgID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractRequest{}
	for rows.Next() {
		var i ContractRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientID,
			&i.ProductID,
			&i.DesiredInstallments,
			&i.DesiredDownPayment,
			&i.Note,
			&i.Status,
			&i.ContractID,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractRequestsByOrg = `-- name: ListContractRequestsByOrg :many
SELECT id, org_id, client_id, product_id, desired_installments, desired_down_payment, note, status, contract_id, created_at, decided_at
FROM contract_requests
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListContractRequestsByOrg(ctx context.Context, orgID pgtype.UUID) ([]ContractRequest, error) {
	rows, err := q.db.Query(ctx, listContractRequestsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContractRequest{}
	for rows.Next() {
		var i ContractRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ClientID,
			&i.ProductID,
			&i.DesiredInstallments,
			&i.DesiredDownPayment,
			&i.Note,
			&i.Status,
			&i.ContractID,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContractRequest = `-- name: UpdateContractRequest :exec
UPDATE contract_requests
SET status = $3, contract_id = $4, decided_at = $5
WHERE id = $1 AND org_id = $2
`

type UpdateContractRequestParams struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Status     string             `json:"status"`
	ContractID pgtype.UUID        `json:"contract_id"`
	DecidedAt  pgtype.Timestamptz `json:"decided_at"`
}

func (q *Queries) UpdateContractRequest(ctx context.Context, arg UpdateContractRequestParams) error {
	_, err := q.db.Exec(ctx, updateContractRequest,
		arg.ID,
		arg.OrgID,
		arg.Status,
		arg.ContractID,
		arg.DecidedAt,
	)
	return err
}
