// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, org_id, name, category, cost_price, halal_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, category, cost_price, halal_status, created_at
`

type CreateProductParams struct {
	ID          pgtype.UUID    `json:"id"`
	OrgID       pgtype.UUID    `json:"org_id"`
	Name        string         `json:"name"`
	Category    string         `json:"category"`
	CostPrice   pgtype.Numeric `json:"cost_price"`
	HalalStatus string         `json:"halal_status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Category,
		arg.CostPrice,
		arg.HalalStatus,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Category,
		&i.CostPrice,
		&i.HalalStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, org_id, name, category, cost_price, halal_status, created_at
FROM products
WHERE id = $1 AND org_id = $2
`

type GetProductByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.OrgID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Category,
		&i.CostPrice,
		&i.HalalStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listProductsByOrg = `-- name: ListProductsByOrg :many
SELECT id, org_id, name, category, cost_price, halal_status, created_at
FROM products
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProductsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Category,
			&i.CostPrice,
			&i.HalalStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $3, category = $4, cost_price = $5, halal_status = $6
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, category, cost_price, halal_status, created_at
`

type UpdateProductParams struct {
	ID          pgtype.UUID    `json:"id"`
	OrgID       pgtype.UUID    `json:"org_id"`
	Name        string         `json:"name"`
	Category    string         `json:"category"`
	CostPrice   pgtype.Numeric `json:"cost_price"`
	HalalStatus string         `json:"halal_status"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Category,
		arg.CostPrice,
		arg.HalalStatus,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Category,
		&i.CostPrice,
		&i.HalalStatus,
		&i.CreatedAt,
	)
	return i, err
}
