package httpserver

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// MountSwagger serves the Swagger UI at /swagger/ documenting the PUBLIC API.
// The OpenAPI spec is served from /swagger/doc.json (spec bytes are provided by
// the caller — generated by `swag` in later phases). The explicit doc.json route
// is registered before the wildcard so chi prefers it.
func MountSwagger(r chi.Router, spec []byte) {
	r.Get("/swagger/doc.json", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write(spec)
	})
	r.Get("/swagger/*", httpSwagger.Handler(httpSwagger.URL("/swagger/doc.json")))
	r.Get("/swagger", http.RedirectHandler("/swagger/index.html", http.StatusMovedPermanently).ServeHTTP)
}
