// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (id, org_id, full_name, phone, document)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, full_name, phone, document, created_at
`

type CreateClientParams struct {
	ID       pgtype.UUID `json:"id"`
	OrgID    pgtype.UUID `json:"org_id"`
	FullName string      `json:"full_name"`
	Phone    string      `json:"phone"`
	Document string      `json:"document"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.OrgID,
		arg.FullName,
		arg.Phone,
		arg.Document,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FullName,
		&i.Phone,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, org_id, full_name, phone, document, created_at
FROM clients
WHERE id = $1 AND org_id = $2
`

type GetClientByIDParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetClientByID(ctx context.Context, arg GetClientByIDParams) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, arg.ID, arg.OrgID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FullName,
		&i.Phone,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}

const listClientsByOrg = `-- name: ListClientsByOrg :many
SELECT id, org_id, full_name, phone, document, created_at
FROM clients
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClientsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClientsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.FullName,
			&i.Phone,
			&i.Document,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET full_name = $3, phone = $4, document = $5
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, full_name, phone, document, created_at
`

type UpdateClientParams struct {
	ID       pgtype.UUID `json:"id"`
	OrgID    pgtype.UUID `json:"org_id"`
	FullName string      `json:"full_name"`
	Phone    string      `json:"phone"`
	Document string      `json:"document"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.OrgID,
		arg.FullName,
		arg.Phone,
		arg.Document,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.FullName,
		&i.Phone,
		&i.Document,
		&i.CreatedAt,
	)
	return i, err
}
