// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (Client, error)
	ListClientsByOrg(ctx context.Context, orgID pgtype.UUID) ([]Client, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
}

var _ Querier = (*Queries)(nil)
