// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, org_id, category, amount, note, spent_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, category, amount, note, spent_at, created_at
`

type CreateExpenseParams struct {
	ID       pgtype.UUID    `json:"id"`
	OrgID    pgtype.UUID    `json:"org_id"`
	Category string         `json:"category"`
	Amount   pgtype.Numeric `json:"amount"`
	Note     string         `json:"note"`
	SpentAt  pgtype.Date    `json:"spent_at"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.OrgID,
		arg.Category,
		arg.Amount,
		arg.Note,
		arg.SpentAt,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Category,
		&i.Amount,
		&i.Note,
		&i.SpentAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :execrows
DELETE FROM expenses
WHERE id = $1 AND org_id = $2
`

type DeleteExpenseParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpensesByOrg = `-- name: ListExpensesByOrg :many
SELECT id, org_id, category, amount, note, spent_at, created_at
FROM expenses
WHERE org_id = $1
ORDER BY spent_at DESC, created_at DESC
`

func (q *Queries) ListExpensesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Category,
			&i.Amount,
			&i.Note,
			&i.SpentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
