// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	DeleteExpense(ctx context.Context, arg DeleteExpenseParams) (int64, error)
	ListExpensesByOrg(ctx context.Context, orgID pgtype.UUID) ([]Expense, error)
}

var _ Querier = (*Queries)(nil)
