// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (id, org_id, name, prefix, key_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, name, prefix, key_hash, created_at, revoked_at
`

type CreateApiKeyParams struct {
	ID      pgtype.UUID `json:"id"`
	OrgID   pgtype.UUID `json:"org_id"`
	Name    string      `json:"name"`
	Prefix  string      `json:"prefix"`
	KeyHash string      `json:"key_hash"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getApiKeyByHash = `-- name: GetApiKeyByHash :one
SELECT id, org_id, name, prefix, key_hash, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listApiKeysByOrg = `-- name: ListApiKeysByOrg :many
SELECT id, org_id, name, prefix, key_hash, created_at, revoked_at
FROM api_keys
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListApiKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeApiKey = `-- name: RevokeApiKey :one
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND org_id = $2 AND revoked_at IS NULL
RETURNING id, org_id, name, prefix, key_hash, created_at, revoked_at
`

type RevokeApiKeyParams struct {
	ID    pgtype.UUID `json:"id"`
	OrgID pgtype.UUID `json:"org_id"`
}

func (q *Queries) RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeApiKey, arg.ID, arg.OrgID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
