// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOrganizations(ctx context.Context) (int64, error)
	CountUsersByEmail(ctx context.Context, email string) (int64, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetApiKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListApiKeysByOrg(ctx context.Context, orgID pgtype.UUID) ([]ApiKey, error)
	ListUsersByOrg(ctx context.Context, orgID pgtype.UUID) ([]User, error)
	RevokeApiKey(ctx context.Context, arg RevokeApiKeyParams) (ApiKey, error)
}

var _ Querier = (*Queries)(nil)
