// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPortalAccountByClientID = `-- name: GetPortalAccountByClientID :one
SELECT client_id, org_id, email, password_hash, created_at
FROM client_portal_accounts
WHERE org_id = $1 AND client_id = $2
`

type GetPortalAccountByClientIDParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) GetPortalAccountByClientID(ctx context.Context, arg GetPortalAccountByClientIDParams) (ClientPortalAccount, error) {
	row := q.db.QueryRow(ctx, getPortalAccountByClientID, arg.OrgID, arg.ClientID)
	var i ClientPortalAccount
	err := row.Scan(
		&i.ClientID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getPortalAccountByEmail = `-- name: GetPortalAccountByEmail :one
SELECT client_id, org_id, email, password_hash, created_at
FROM client_portal_accounts
WHERE email = $1
`

func (q *Queries) GetPortalAccountByEmail(ctx context.Context, email string) (ClientPortalAccount, error) {
	row := q.db.QueryRow(ctx, getPortalAccountByEmail, email)
	var i ClientPortalAccount
	err := row.Scan(
		&i.ClientID,
		&i.OrgID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPortalAccount = `-- name: UpsertPortalAccount :exec
INSERT INTO client_portal_accounts (client_id, org_id, email, password_hash)
VALUES ($1, $2, $3, $4)
ON CONFLICT (client_id) DO UPDATE
    SET email = EXCLUDED.email, password_hash = EXCLUDED.password_hash
`

type UpsertPortalAccountParams struct {
	ClientID     pgtype.UUID `json:"client_id"`
	OrgID        pgtype.UUID `json:"org_id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpsertPortalAccount(ctx context.Context, arg UpsertPortalAccountParams) error {
	_, err := q.db.Exec(ctx, upsertPortalAccount,
		arg.ClientID,
		arg.OrgID,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}
