// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureConversation = `-- name: EnsureConversation :one
INSERT INTO conversations (id, org_id, client_id)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, client_id) DO UPDATE SET org_id = EXCLUDED.org_id
RETURNING id, org_id, client_id, created_at, last_message_at
`

type EnsureConversationParams struct {
	ID       pgtype.UUID `json:"id"`
	OrgID    pgtype.UUID `json:"org_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) EnsureConversation(ctx context.Context, arg EnsureConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, ensureConversation, arg.ID, arg.OrgID, arg.ClientID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ClientID,
		&i.CreatedAt,
		&i.LastMessageAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, conversation_id, org_id, sender_kind, sender_id, body)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, org_id, sender_kind, sender_id, body, created_at
`

type InsertMessageParams struct {
	ID             pgtype.UUID `json:"id"`
	ConversationID pgtype.UUID `json:"conversation_id"`
	OrgID          pgtype.UUID `json:"org_id"`
	SenderKind     string      `json:"sender_kind"`
	SenderID       pgtype.UUID `json:"sender_id"`
	Body           string      `json:"body"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.OrgID,
		arg.SenderKind,
		arg.SenderID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.SenderKind,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT c.id, c.client_id, c.last_message_at,
       COALESCE(lm.body, '')        AS last_body,
       COALESCE(lm.sender_kind, '') AS last_sender_kind
FROM conversations c
LEFT JOIN LATERAL (
    SELECT body, sender_kind
    FROM messages mm
    WHERE mm.conversation_id = c.id
    ORDER BY mm.created_at DESC
    LIMIT 1
) lm ON true
WHERE c.org_id = $1
ORDER BY c.last_message_at DESC
`

type ListConversationsRow struct {
	ID             pgtype.UUID        `json:"id"`
	ClientID       pgtype.UUID        `json:"client_id"`
	LastMessageAt  pgtype.Timestamptz `json:"last_message_at"`
	LastBody       string             `json:"last_body"`
	LastSenderKind string             `json:"last_sender_kind"`
}

func (q *Queries) ListConversations(ctx context.Context, orgID pgtype.UUID) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.LastMessageAt,
			&i.LastBody,
			&i.LastSenderKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByClient = `-- name: ListMessagesByClient :many
SELECT m.id, m.conversation_id, m.org_id, m.sender_kind, m.sender_id, m.body, m.created_at
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.org_id = $1 AND c.client_id = $2
ORDER BY m.created_at ASC
`

type ListMessagesByClientParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	ClientID pgtype.UUID `json:"client_id"`
}

func (q *Queries) ListMessagesByClient(ctx context.Context, arg ListMessagesByClientParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByClient, arg.OrgID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.SenderKind,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET last_message_at = now() WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
