// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	EnsureConversation(ctx context.Context, arg EnsureConversationParams) (Conversation, error)
	GetPortalAccountByClientID(ctx context.Context, arg GetPortalAccountByClientIDParams) (ClientPortalAccount, error)
	GetPortalAccountByEmail(ctx context.Context, email string) (ClientPortalAccount, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListConversations(ctx context.Context, orgID pgtype.UUID) ([]ListConversationsRow, error)
	ListMessagesByClient(ctx context.Context, arg ListMessagesByClientParams) ([]Message, error)
	TouchConversation(ctx context.Context, id pgtype.UUID) error
	UpsertPortalAccount(ctx context.Context, arg UpsertPortalAccountParams) error
}

var _ Querier = (*Queries)(nil)
